# Generated by Django 4.2.8 on 2024-01-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1990-04-23'),
            preserve_default=False,
        ),
    ]
